services:
  app:
    build: .
    container_name: app
    ports:
      - 8501:8501
    depends_on:
      - ollama
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    entrypoint: ["/bin/bash", "-c"]
    command: >
      "ollama serve &
      pid=$!
      sleep 5 &&
      while read -r line; do ollama pull "$$line"; done < /models.txt &&
      wait $$pid"
    volumes:
      - ${PWD}/models.txt:/models.txt
      - ollama:/root/.ollama
volumes:
  ollama:
