services:
  app:
    build: .
    container_name: app
    environment:
      - OLLAMA_HOST=http://ollama:11434
    volumes:
      - ${PWD}/pages:/app/pages:rw
    ports:
      - 8501:8501
    depends_on:
      - ollama
      - pgvector
  # docker compose exec -it pgvector psql -hpgvector -dollama -U postgres -c"\dx"
  pgvector:
    image: pgvector/pgvector:pg17
    container_name: pgvector
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=ollama
      # allow all connections
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    entrypoint: ["/bin/bash", "-c"]
    command: >
      "ollama serve &
      pid=$!
      sleep 5 &&
      while read -r line; do ollama pull "$$line"; done < /models.txt &&
      wait $$pid"
    volumes:
      - ${PWD}/models.txt:/models.txt
      - ollama:/root/.ollama
    ports:
      - 11434:11434
volumes:
  ollama:
